import { useCallback, useEffect, useRef, useState } from 'react';
import { Maximize2, Minus, Plus, LocateFixed, MousePointer2 } from 'lucide-react';
import type { Chart, ChartNode } from '../core/graph';
export const chartColors = (dark: boolean) => dark ? { background: '#191c1e', text: '#e7eae4', edge: '#818b91', normal: '#242a2d', outline: '#576267', decision: '#2c3321', decisionStroke: '#b8d872', io: '#203038', ioStroke: '#7199ac', terminator: '#303a22', terminatorStroke: '#a3c967', call: '#2e273a', callStroke: '#a593bf', selected: '#dcff8c' } : { background: '#fafbf8', text: '#27312b', edge: '#738078', normal: '#ffffff', outline: '#a2ada5', decision: '#f1f8df', decisionStroke: '#799c39', io: '#eef6fa', ioStroke: '#688b9d', terminator: '#eef7dc', terminatorStroke: '#799c39', call: '#f4effa', callStroke: '#9b85b5', selected: '#4e790f' };
export function ChartArtwork({ chart, dark, selectedLine = 0, onSelect, exportMode = false }: { chart: Chart; dark: boolean; selectedLine?: number; onSelect?: (node: ChartNode) => void; exportMode?: boolean }) {
  const c = chartColors(dark);
  return <>
    <defs><marker id="chart-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill={c.edge}/></marker></defs>
    {chart.edges.map(e => { const first = e.points[0], second = e.points[1] || first; const horizontal = first.y === second.y; const x = horizontal ? (first.x + second.x) / 2 : first.x + 17, y = horizontal ? first.y - 10 : first.y + 25; return <g key={e.id}><polyline fill="none" stroke={c.edge} strokeWidth="1.6" strokeLinejoin="round" points={e.points.map(p => `${p.x},${p.y}`).join(' ')} markerEnd={chart.nodes.find(n => n.id === e.to)?.kind === 'join' ? undefined : 'url(#chart-arrow)'}/>{e.label && <text x={x} y={y} textAnchor={horizontal ? 'middle' : 'start'} fill={c.text} fontSize="11" fontWeight="500" fontFamily="Arial, sans-serif" stroke={c.background} strokeWidth="5" paintOrder="stroke">{e.label}</text>}</g>; })}
    {chart.nodes.map(n => {
      const active = !exportMode && n.line === selectedLine && n.kind !== 'join';
      const fill = n.kind === 'decision' ? c.decision : n.kind === 'input' || n.kind === 'output' ? c.io : n.kind === 'start' || n.kind === 'end' ? c.terminator : n.kind === 'call' ? c.call : c.normal;
      const stroke = active ? c.selected : n.kind === 'decision' ? c.decisionStroke : n.kind === 'input' || n.kind === 'output' ? c.ioStroke : n.kind === 'start' || n.kind === 'end' ? c.terminatorStroke : n.kind === 'call' ? c.callStroke : c.outline;
      return <g key={n.id} transform={`translate(${n.x} ${n.y})`} onClick={onSelect ? e => { e.stopPropagation(); onSelect(n); } : undefined} onKeyDown={onSelect ? e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(n); } } : undefined} tabIndex={onSelect && n.kind !== 'join' ? 0 : undefined} role={onSelect && n.kind !== 'join' ? 'button' : undefined} aria-label={`${n.label}. Line ${n.line}`} style={{ cursor: onSelect ? 'pointer' : 'default', outline: 'none' }} className={active ? 'chart-node active' : 'chart-node'}>
        <title>{n.kind === 'join' ? 'Flow joins' : `${n.label} · Line ${n.line}`}</title>
        {n.kind === 'join' ? <circle cx="5" cy="5" r="4" fill={c.edge}/> : n.kind === 'decision' ? <path d={`M ${n.width / 2} 0 L ${n.width} ${n.height / 2} L ${n.width / 2} ${n.height} L 0 ${n.height / 2} Z`} fill={fill} stroke={stroke} strokeWidth={active ? 2.5 : 1.5}/> : n.kind === 'input' || n.kind === 'output' ? <path d={`M 20 0 H ${n.width} L ${n.width - 20} ${n.height} H 0 Z`} fill={fill} stroke={stroke} strokeWidth={active ? 2.5 : 1.5}/> : <rect width={n.width} height={n.height} rx={n.kind === 'start' || n.kind === 'end' ? n.height / 2 : 5} fill={fill} stroke={stroke} strokeWidth={active ? 2.5 : 1.5}/>}
        {n.kind === 'call' && <><path d={`M 10 0 V ${n.height} M ${n.width - 10} 0 V ${n.height}`} stroke={stroke} strokeWidth="1.5"/></>}
        {n.kind !== 'join' && <text x={n.width / 2} y={n.height / 2 - (n.lines.length - 1) * 10} textAnchor="middle" dominantBaseline="central" fill={c.text} fontSize="13.5" fontFamily="'Courier New', monospace" fontWeight={n.kind === 'start' || n.kind === 'end' ? 600 : 400}>{n.lines.map((line, i) => <tspan key={i} x={n.width / 2} dy={i ? 20 : 0}>{line}</tspan>)}</text>}
      </g>;
    })}
  </>;
}
export function Diagram({ chart, dark, selectedLine, onSelect, stale, resetKey }: { resetKey: string; chart: Chart | null; dark: boolean; selectedLine: number; onSelect: (node: ChartNode) => void; stale: boolean }) {
  const viewport = useRef<HTMLDivElement>(null); const [view, setView] = useState({ x: 0, y: 0, scale: 1 });
  const [size, setSize] = useState({ width: 700, height: 650 });
  const drag = useRef<{ x: number; y: number; originalX: number; originalY: number; moved: boolean } | null>(null);
  const fitted = useRef('');
  useEffect(() => { const el = viewport.current!; const observer = new ResizeObserver(entries => { const { width, height } = entries[0].contentRect; setSize({ width, height }); }); observer.observe(el); return () => observer.disconnect(); }, []);
  const fit = useCallback(() => { if (!chart) return; const scale = Math.min((size.width - 72) / chart.width, (size.height - 82) / chart.height, 1.1); setView({ x: (size.width - chart.width * scale) / 2, y: (size.height - chart.height * scale) / 2, scale: Math.max(.06, scale) }); }, [chart, size]);
  useEffect(() => { if (!chart) return; const key = resetKey; if (fitted.current !== key || fitted.current === '') { fit(); fitted.current = key; } }, [chart, fit, resetKey]);
  // Refit when the viewport changes (for example, a mobile panel opens).
  useEffect(() => { fit(); }, [size.width, size.height]);
  function zoom(amount: number, x = size.width / 2, y = size.height / 2) { setView(v => { const scale = Math.min(3, Math.max(.06, v.scale * amount)); const ratio = scale / v.scale; return { scale, x: x - (x - v.x) * ratio, y: y - (y - v.y) * ratio }; }); }
  useEffect(() => { const el = viewport.current!; const wheel = (e: WheelEvent) => { e.preventDefault(); if (e.ctrlKey || e.metaKey) { const box = el.getBoundingClientRect(); zoom(Math.exp(-e.deltaY * .004), e.clientX - box.left, e.clientY - box.top); } else setView(v => ({ ...v, x: v.x - e.deltaX, y: v.y - e.deltaY })); }; el.addEventListener('wheel', wheel, { passive: false }); return () => el.removeEventListener('wheel', wheel); }, [size]);
  return <div className={`diagram-viewport ${dark ? 'dark-canvas' : 'light-canvas'}`} ref={viewport} onPointerDown={e => { if ((e.target as Element).closest('.canvas-controls, .canvas-badge, .chart-node')) return; drag.current = { x: e.clientX, y: e.clientY, originalX: view.x, originalY: view.y, moved: false }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (!drag.current) return; const dx = e.clientX - drag.current.x, dy = e.clientY - drag.current.y; if (Math.abs(dx) + Math.abs(dy) > 3) drag.current.moved = true; setView(v => ({ ...v, x: drag.current!.originalX + dx, y: drag.current!.originalY + dy })); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}>
    <div className="canvas-badge"><span className={`status-dot ${stale ? 'warning' : ''}`} />{stale ? 'Last valid chart' : 'Live preview'}</div>
    {chart ? <svg className="diagram-svg" width="100%" height="100%" aria-label={`${chart.name} flowchart`}><g transform={`translate(${view.x} ${view.y}) scale(${view.scale})`}><ChartArtwork chart={chart} dark={dark} selectedLine={selectedLine} onSelect={onSelect}/></g></svg> : <div className="empty-chart"><MousePointer2 size={28}/><h3>Your logic starts here</h3><p>Write pseudocode or pick an example to build a flowchart.</p></div>}
    <div className="canvas-bottom"><span className="canvas-hint">Drag to pan <span>·</span> Ctrl / ⌘ + scroll to zoom</span><div className="canvas-controls"><button aria-label="Zoom out" title="Zoom out" onClick={() => zoom(1 / 1.2)}><Minus size={15}/></button><span>{Math.round(view.scale * 100)}%</span><button aria-label="Zoom in" title="Zoom in" onClick={() => zoom(1.2)}><Plus size={15}/></button><i/><button aria-label="Fit chart" title="Fit chart" onClick={fit}><Maximize2 size={15}/></button><button aria-label="Actual size" title="Actual size" onClick={() => { if (chart) setView({ scale: 1, x: (size.width - chart.width) / 2, y: 28 }); }}><LocateFixed size={15}/></button></div></div>
  </div>;
}
