import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { chromium } from '@playwright/test';
import { createServer } from 'vite';
const root = new URL('../', import.meta.url).pathname;
const server = await createServer({ root, server: { host: '127.0.0.1', port: 5173, strictPort: true } });
await server.listen();
let browser;
try {
  browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
  const origin = 'http://127.0.0.1:5173/Codechart/';
  const editor = page.getByRole('textbox', { name: 'Pseudocode editor' });
  const edit = async code => { await editor.click(); await page.keyboard.press('ControlOrMeta+A'); await page.keyboard.insertText(code); };
  const close = async () => { await page.getByRole('button', { name: 'Close dialog', exact: true }).click(); };
  await page.goto(origin); await page.getByText('Valid structure', { exact: true }).waitFor();
  assert.equal(await page.locator('.chart-node').count(), 9);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  const lineRect = await page.locator('.cm-line').first().boundingBox(); const numberRect = await page.locator('.cm-lineNumbers .cm-gutterElement').filter({ hasText: /^1$/ }).boundingBox();
  assert.ok(Math.abs(lineRect.y - numberRect.y) < 4, 'Gutter must align with source');
  await page.getByRole('button', { name: 'Output pay. Line 13', exact: true }).click();
  await page.getByText('Ln 13', { exact: false }).waitFor();
  await edit('START\nIF flag\nOUTPUT flag\nEND');
  await page.getByText('Last valid chart', { exact: true }).waitFor(); assert.equal(await page.getByRole('button', { name: 'Export', exact: true }).isDisabled(), true);
  await page.locator('.validation-button').click(); await page.getByText('IF has no matching ENDIF.', { exact: true }).waitFor();
  await edit('START\nIF x\nOUTPUT x\nELSE\nOUTPUT "none"\nENDIF\nEND');
  await page.getByText('Valid structure', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Format', exact: true }).click(); assert.match(await editor.innerText(), /\s+OUTPUT x/);
  await page.getByRole('button', { name: 'Examples', exact: true }).click();
  await page.getByRole('button', { name: /Employee net pay/ }).click();
  await page.getByRole('combobox', { name: 'Chart module' }).selectOption('finish');
  await page.getByRole('button', { name: /Output employeeCount\. Line/ }).waitFor();
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  const svgDownload = page.waitForEvent('download'); await page.getByRole('button', { name: /^SVG / }).click();
  const svg = await svgDownload; const svgPath = await svg.path(); const svgText = await fs.readFile(svgPath, 'utf8'); assert.match(svgText, /<svg/); assert.match(svgText, /employeeCount/);
  const pngDownload = page.waitForEvent('download'); await page.getByRole('button', { name: /^PNG / }).click();
  const png = await pngDownload; const pngData = await fs.readFile(await png.path()); assert.equal(pngData.readUInt32BE(0), 0x89504e47);
  const popupEvent = page.waitForEvent('popup'); await page.getByRole('button', { name: /^Print \/ PDF / }).click(); const popup = await popupEvent; await popup.waitForLoadState(); assert.equal(await popup.locator('svg').count(), 1); await popup.close(); await close();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('button', { name: 'Share', exact: true }).click(); const share = await page.getByLabel('Project link', { exact: true }).inputValue(); assert.match(share, /#project=/);
  const sharedPage = await context.newPage(); await sharedPage.goto(share); await sharedPage.getByText('Valid structure', { exact: true }).waitFor(); assert.equal(await sharedPage.getByLabel('Project title', { exact: true }).inputValue(), 'Employee net pay'); await sharedPage.close(); await close();
  await page.locator('input[type=file]').setInputFiles({ name: 'test.flow', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ format: 'codechart', version: 1, title: 'Imported ✓', source: 'START\nOUTPUT "hello"\nEND' })) });
  await page.getByRole('button', { name: 'Output "hello". Line 2', exact: true }).waitFor(); assert.equal(await page.getByLabel('Project title', { exact: true }).inputValue(), 'Imported ✓');
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.flow', mimeType: 'application/json', buffer: Buffer.from('{}') }); await page.getByText('Unsupported project format.', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Examples', exact: true }).click(); await page.getByRole('button', { name: /Overtime pay/ }).click();
  await page.getByRole('button', { name: 'Fit chart', exact: true }).click();
  await page.screenshot({ path: '/tmp/codechart-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await editor.isVisible(), true);
  await page.getByRole('button', { name: 'Flowchart', exact: true }).click(); await page.getByRole('button', { name: 'Fit chart', exact: true }).click();
  assert.equal(await editor.isVisible(), false); assert.equal(await page.locator('.diagram-viewport').isVisible(), true);
  await page.screenshot({ path: '/tmp/codechart-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Share', exact: true }).click(); await close();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: editing, diagnostics, source mapping, modules, SVG/PNG/PDF, save/share/import, desktop/mobile, and no runtime errors.');
} finally { await browser?.close(); await server.close(); }
