import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowUpRight, BookOpen, Braces, Check, ChevronDown, ChevronRight, CircleAlert, Code2, Copy, FilePlus2, FileText, FolderOpen, GitBranch, Github, LayoutTemplate, Link2, Loader2, Moon, MoreHorizontal, Plus, Redo2, Save, Settings2, ShieldCheck, Sparkles, Sun, Undo2, Wand2, X } from 'lucide-react';
import { Editor, type EditorHandle } from './components/Editor';
import { Diagram } from './components/Diagram';
import { parse, formatCode, type Program } from './core/parser';
import { buildChart } from './core/graph';
import { examples, snippets, type Example } from './core/examples';
import { decodeShare, download, filename, makeProject, readProject, shareURL, type Project } from './core/projects';
const DRAFT_KEY = 'codechart:draft:v1', PROJECTS_KEY = 'codechart:projects:v1';
type Modal = 'examples' | 'language' | 'projects' | 'export' | 'settings' | 'share' | null;
function initial() {
  let error = '';
  try { const shared = decodeShare(location.hash); if (shared) return { project: shared, error }; } catch (e) { error = (e as Error).message; }
  try { const raw = localStorage.getItem(DRAFT_KEY); if (raw) return { project: readProject(JSON.parse(raw)), error }; } catch { /* A bad draft should not prevent opening the editor. */ }
  return { project: makeProject('Overtime pay', examples[0].code), error };
}
function readSaved(): Project[] { try { return (JSON.parse(localStorage.getItem(PROJECTS_KEY) || '[]') as unknown[]).map(readProject); } catch { return []; } }
function Logo({ small = false }: { small?: boolean }) { return <span className={`brand ${small ? 'small' : ''}`}><span className="brand-symbol"><GitBranch size={22} strokeWidth={2.5}/></span>{!small && <>codechart<span className="alpha-label">ALPHA</span></>}</span>; }
function Dialog({ title, eyebrow, children, onClose, wide = false }: { title: string; eyebrow?: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement; const root = ref.current!; root.focus();
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { e.preventDefault(); onClose(); }
      if (e.key === 'Tab') { const controls = [...root.querySelectorAll<HTMLElement>('button:not(:disabled), input, textarea, select, a[href], [tabindex="0"]')].filter(el => el.offsetParent !== null); const first = controls[0], last = controls.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === root)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }
    };
    document.addEventListener('keydown', handler); return () => { document.removeEventListener('keydown', handler); previous?.focus(); };
  }, [onClose]);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><div className="modal-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</div></div>;
}
export default function App() {
  const [start] = useState(initial), [source, setSource] = useState(start.project.source), [title, setTitle] = useState(start.project.title);
  const [dark, setDark] = useState(() => { try { return localStorage.getItem('codechart:theme') !== 'light'; } catch { return true; } });
  const [canvasDark, setCanvasDark] = useState(false), [moduleName, setModuleName] = useState('@main'), [selectedLine, setSelectedLine] = useState(1);
  const [modal, setModal] = useState<Modal>(null), [toast, setToast] = useState(start.error), [saved, setSaved] = useState(readSaved), [storageError, setStorageError] = useState(false);
  const [problemsOpen, setProblemsOpen] = useState(false), [activeMobile, setActiveMobile] = useState<'code' | 'chart'>('code');
  const [shareLink, setShareLink] = useState(''), [exportBusy, setExportBusy] = useState(false), [exportDark, setExportDark] = useState(false), [split, setSplit] = useState(43);
  const [exampleQuery, setExampleQuery] = useState('');
  const editor = useRef<EditorHandle>(null), fileInput = useRef<HTMLInputElement>(null), workspace = useRef<HTMLDivElement>(null);
  const program = useMemo(() => parse(source), [source]);
  const errors = program.diagnostics.filter(d => d.severity === 'error'), warnings = program.diagnostics.filter(d => d.severity === 'warning');
  const lastValid = useRef<Program | null>(errors.length ? null : program);
  useEffect(() => { if (!errors.length) lastValid.current = program; }, [program]);
  const valid = errors.length ? lastValid.current : program;
  const chart = useMemo(() => valid && source.trim() ? buildChart(valid, moduleName) : null, [valid, moduleName, !!source.trim()]);
  const stale = errors.length > 0;
  const nodes = chart?.nodes.filter(n => n.kind !== 'join').length || 0;
  const decisions = chart?.nodes.filter(n => n.kind === 'decision').length || 0;
  const closeModal = useMemo(() => () => setModal(null), []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; try { localStorage.setItem('codechart:theme', dark ? 'dark' : 'light'); } catch { /* Theme remains usable without storage. */ } }, [dark]);
  useEffect(() => { const timer = setTimeout(() => { try { localStorage.setItem(DRAFT_KEY, JSON.stringify(makeProject(title, source))); setStorageError(false); } catch { setStorageError(true); } }, 500); return () => clearTimeout(timer); }, [title, source]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 5000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!program.modules.some(m => m.name === moduleName) && moduleName !== '@main' && !stale) setModuleName('@main'); }, [program, moduleName, stale]);
  function archive() {
    const project = makeProject(title, source); const next = [project, ...saved.filter(p => p.title !== title || p.source !== source)].slice(0, 20);
    setSaved(next); try { localStorage.setItem(PROJECTS_KEY, JSON.stringify(next)); } catch { setStorageError(true); } return project;
  }
  function load(project: Project) { archive(); setTitle(project.title); setSource(project.source); setModuleName('@main'); setModal(null); setSelectedLine(1); history.replaceState(null, '', location.pathname + location.search); }
  function loadExample(example: Example) { load(makeProject(example.title, example.code)); setToast('Example loaded. Your previous work is in Projects.'); }
  function save() { const project = archive(); download(new Blob([JSON.stringify(project, null, 2)], { type: 'application/json' }), `${filename(title)}.flow`); setToast('Project saved. Open the .flow file to continue anywhere.'); }
  async function openFile(file: File) { try { if (file.size > 150000) throw new Error('Choose a project smaller than 150 KB.'); const text = await file.text(); const project = /\.(txt|pseudo)$/i.test(file.name) ? makeProject(file.name.replace(/\.[^.]+$/, ''), text) : readProject(JSON.parse(text)); load(project); setToast('Project opened.'); } catch (e) { setToast((e as Error).message); } }
  function share() { try { setShareLink(shareURL(makeProject(title, source))); setModal('share'); } catch (e) { setToast((e as Error).message); } }
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); setToast('Copied to clipboard.'); } catch { setToast('Clipboard access is blocked. Select the text and copy it manually.'); } }
  useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 's') { e.preventDefault(); save(); } if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key.toLowerCase() === 'f') { e.preventDefault(); setSource(formatCode(source)); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [source, title, saved]);
  async function doExport(kind: 'svg' | 'png' | 'pdf') { if (!chart || stale) return; setExportBusy(true); try { const { exportPNG, exportSVG, printChart } = await import('./core/export'); if (kind === 'svg') exportSVG(chart, title, exportDark); else if (kind === 'png') await exportPNG(chart, title, exportDark); else printChart(chart, title); if (kind !== 'pdf') setToast(`${kind.toUpperCase()} exported.`); } catch (e) { setToast((e as Error).message); } finally { setExportBusy(false); } }
  const filteredExamples = examples.filter(e => `${e.title} ${e.category} ${e.description}`.toLowerCase().includes(exampleQuery.toLowerCase()));
  return <div className="app-shell">
    <header className="app-header"><a className="brand-link" href="./" aria-label="Codechart home" onClick={e => e.preventDefault()}><Logo/></a><nav aria-label="Main navigation"><button className="nav-button selected" onClick={() => setModal(null)}>Workspace</button><button className="nav-button" onClick={() => setModal('examples')}>Examples <span className="count-tag">7</span></button><button className="nav-button" onClick={() => setModal('language')}>Language guide <ArrowUpRight size={13}/></button></nav><div className="header-actions"><span className="local-badge"><ShieldCheck size={13}/> Runs in your browser</span><button className="icon-button" onClick={() => setDark(!dark)} aria-label={dark ? 'Use light theme' : 'Use dark theme'} title="Toggle theme">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><a className="icon-button github-link" aria-label="Codechart on GitHub" href="https://github.com/JPLuker/Codechart" target="_blank" rel="noreferrer"><Github size={18}/></a></div></header>
    <div className="app-body"><aside className="rail" aria-label="Workspace tools"><div className="rail-top"><button className="rail-button active" title="Editor" aria-label="Editor" onClick={() => { setModal(null); editor.current?.focus(); }}><Braces size={21}/></button><button className="rail-button" title="Projects" aria-label="Projects" onClick={() => setModal('projects')}><FolderOpen size={20}/></button><button className="rail-button" title="Examples" aria-label="Examples" onClick={() => setModal('examples')}><LayoutTemplate size={20}/></button><button className="rail-button" title="Language guide" aria-label="Language guide" onClick={() => setModal('language')}><BookOpen size={20}/></button></div><div className="rail-bottom"><button className="rail-button" title="Settings" aria-label="Settings" onClick={() => setModal('settings')}><Settings2 size={20}/></button><span className="rail-version">0.1</span></div></aside>
    <main className="main"><section className="workspace-intro"><div><div className="eyebrow"><span/> FROM THOUGHT TO FLOW</div><h1>Make your logic visible<span>.</span></h1><p>Write the steps. See the structure. Get the flowchart.</p></div><button className="starter-button" onClick={() => setModal('examples')}><Sparkles size={16}/><span>Start with an example</span><ArrowUpRight size={16}/></button></section>
    <section className="workbench" aria-label="Pseudocode flowchart workspace"><div className="project-toolbar"><div className="project-title"><span className="file-icon"><FileText size={17}/></span><input aria-label="Project title" maxLength={120} value={title} onChange={e => setTitle(e.target.value)} placeholder="Untitled project"/><span className="draft-status"><span className={`status-dot ${storageError ? 'warning' : ''}`}/>{storageError ? 'Save unavailable' : 'Autosaved locally'}</span></div><div className="project-actions"><button className="text-button" aria-label="Open" onClick={() => setModal('projects')} title="Open project"><FolderOpen size={15}/><span>Open</span></button><button className="text-button" aria-label="Save" onClick={save} title="Save project (Ctrl / ⌘ + S)"><Save size={15}/><span>Save</span></button><span className="divider"/><button className="text-button" aria-label="Share" onClick={share}><Link2 size={15}/><span>Share</span></button><button className="primary-button" onClick={() => setModal('export')} disabled={!chart || stale}><ArrowDownToLine size={15}/>Export<ChevronDown size={13}/></button></div></div>
    <div className="mobile-tabs"><button className={activeMobile === 'code' ? 'active' : ''} onClick={() => setActiveMobile('code')}><Code2 size={15}/> Pseudocode</button><button className={activeMobile === 'chart' ? 'active' : ''} onClick={() => setActiveMobile('chart')}><GitBranch size={15}/> Flowchart</button></div>
    <div className={`workspace mobile-${activeMobile}`} ref={workspace} style={{ '--editor-width': `${split}%` } as React.CSSProperties}>
      <div className="editor-pane"><div className="pane-heading"><div className="pane-label"><Code2 size={16}/><h2>Pseudocode</h2><span className="file-type">.pseudo</span></div><div className="editor-actions"><button className="icon-button" aria-label="Undo" title="Undo (Ctrl / ⌘ + Z)" onClick={() => editor.current?.undo()}><Undo2 size={15}/></button><button className="icon-button" aria-label="Redo" title="Redo" onClick={() => editor.current?.redo()}><Redo2 size={15}/></button><span className="divider"/><button className="text-button format-button" onClick={() => { setSource(formatCode(source)); setToast('Indentation formatted.'); }} title="Format indentation (Ctrl / ⌘ + Shift + F)"><Wand2 size={14}/>Format</button></div></div><Editor ref={editor} value={source} diagnostics={program.diagnostics} onChange={setSource} onLine={setSelectedLine}/><div className="editor-footer"><button onClick={() => setModal('language')}><span className="status-dot"/> Structured pseudocode <ChevronDown size={12}/></button><span>Ln {selectedLine} <span>·</span> {source.split('\n').length} lines</span></div></div>
      <div className="split-handle" role="separator" aria-label="Resize editor" aria-orientation="vertical" tabIndex={0} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); setSplit(s => Math.max(27, Math.min(65, s + (e.key === 'ArrowLeft' ? -2 : 2)))); } }} onPointerDown={e => { const root = workspace.current!; e.currentTarget.setPointerCapture(e.pointerId); const move = (event: PointerEvent) => { const r = root.getBoundingClientRect(); setSplit(Math.max(27, Math.min(65, (event.clientX - r.left) / r.width * 100))); }; const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); window.removeEventListener('pointercancel', stop); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); window.addEventListener('pointercancel', stop); }}/>
      <div className="chart-pane"><div className="pane-heading"><div className="pane-label"><GitBranch size={16}/><h2>Flowchart</h2>{valid && valid.modules.length > 0 && <select aria-label="Chart module" value={moduleName} onChange={e => setModuleName(e.target.value)}><option value="@main">Main program</option>{valid.modules.map(m => <option key={m.name} value={m.name}>{m.name}()</option>)}</select>}</div><div className="chart-actions"><span className="auto-layout"><span/> Auto layout</span><button className="icon-button" aria-label={canvasDark ? 'Use light canvas' : 'Use dark canvas'} title="Toggle canvas theme" onClick={() => setCanvasDark(!canvasDark)}>{canvasDark ? <Sun size={15}/> : <Moon size={15}/>}</button></div></div><Diagram resetKey={`${title}:${moduleName}`} chart={chart} dark={canvasDark} selectedLine={selectedLine} stale={stale} onSelect={n => { if (stale) return; editor.current?.line(n.line); setActiveMobile('code'); }}/><div className="chart-footer"><span><MouseIcon/> Click a shape to find its code</span><div><span className="symbol process"/>Process<span className="symbol decision"/>Decision<span className="symbol io"/>I/O</div></div></div>
    </div>
    <div className={`validation-bar ${stale ? 'has-errors' : ''}`}><button className="validation-button" onClick={() => setProblemsOpen(!problemsOpen)}>{stale ? <CircleAlert size={15}/> : <Check size={15}/>}<strong>{stale ? `${errors.length} ${errors.length === 1 ? 'error' : 'errors'} to fix` : 'Valid structure'}</strong>{warnings.length > 0 && <span className="warning-count">{warnings.length} {warnings.length === 1 ? 'note' : 'notes'}</span>}<ChevronDown className={problemsOpen ? 'rotated' : ''} size={13}/></button><span className="chart-counts">{nodes} nodes <i/> {decisions} decisions <i/> {chart?.edges.length || 0} connections</span><span className="validation-right">{stale ? 'Exports pause until errors are fixed' : 'Ready when you are'}<span className="status-dot"/></span></div>
    {problemsOpen && <div className="problems-panel" role="region" aria-label="Validation details">{program.diagnostics.length ? program.diagnostics.map((d, i) => <button className={`problem ${d.severity}`} key={`${d.line}-${i}`} onClick={() => editor.current?.line(d.line)}><CircleAlert size={14}/><span className="problem-line">Line {d.line}</span><span>{d.message}</span><ChevronRight size={14}/></button>) : <div className="no-problems"><Check size={16}/> All blocks are balanced. Your structure is ready to export.</div>}</div>}
    </section>
    <section className="quick-insert" aria-label="Insert pseudocode"><span className="quick-label"><Plus size={14}/> Quick insert</span>{snippets.slice(0, 8).map(s => <button key={s.label} onClick={() => editor.current?.insert(s.code)} title={s.hint}>{s.label}</button>)}<button className="more-insert" aria-label="More language options" onClick={() => setModal('language')}><MoreHorizontal size={17}/></button></section>
    <footer className="page-footer"><span><ShieldCheck size={13}/> Your code stays on this device. No account. No AI.</span><span>Made by Joseph Luker <span>·</span> <a href="https://github.com/JPLuker/Codechart" target="_blank" rel="noreferrer">Codechart 0.1.0 alpha <ArrowUpRight size={11}/></a></span></footer>
    </main></div>
    {modal === 'examples' && <Dialog title="A starting point for your logic." eyebrow="EXAMPLE LIBRARY" onClose={closeModal} wide><p className="modal-description">Explore a structure, then make it your own. Your current work is kept in Projects.</p><input className="search-input" placeholder="Find an example…" aria-label="Search examples" value={exampleQuery} onChange={e => setExampleQuery(e.target.value)}/><div className="example-grid">{filteredExamples.map((e, i) => <button key={e.id} className="example-card" onClick={() => loadExample(e)}><div><span className="example-number">0{i + 1}</span><ArrowUpRight size={18}/></div><span className="example-category">{e.category}</span><h3>{e.title}</h3><p>{e.description}</p><span className="example-open">Open example <ChevronRight size={13}/></span></button>)}</div>{!filteredExamples.length && <p className="empty-projects">No examples match that search.</p>}</Dialog>}
    {modal === 'language' && <Dialog title="Small language. Clear logic." eyebrow="LANGUAGE REFERENCE" onClose={closeModal} wide><p className="modal-description">Keywords are case-insensitive. Indentation is for readability; closing keywords define the blocks. Expressions are displayed, never executed.</p><div className="reference-list">{[{ label: 'Start / End', hint: 'Wrap the main program', code: 'START\n    // your steps here\nEND' }, ...snippets, { label: 'Stop / Return', hint: 'End a path; RETURN is for modules', code: 'STOP\n// In a module:\nRETURN' }, { label: 'Comments', hint: 'Ignored outside quoted strings', code: '// a comment\n# another comment' }].map(s => <div className="reference-row" key={s.label}><div><h3>{s.label}</h3><p>{s.hint}</p></div><pre>{s.code}</pre><button className="icon-button" aria-label={`Insert ${s.label}`} title="Insert at cursor" onClick={() => { setModal(null); editor.current?.insert(s.code); }}><Plus size={16}/></button></div>)}</div><div className="guide-note"><CircleAlert size={17}/><p>Define modules after the main program’s END. IF uses a nested IF inside ELSE for additional choices. INPUT/OUTPUT also accept READ/PRINT/DISPLAY. Assignments can omit SET. FOR bounds are inclusive; STEP is a nonzero number.</p></div></Dialog>}
    {modal === 'projects' && <Dialog title="Your workspace, kept close." eyebrow="PROJECTS" onClose={closeModal}><div className="project-menu-actions"><button className="action-card" onClick={() => { load(makeProject('Untitled project', 'START\n\nEND')); setToast('New project. Your previous work is in Projects.'); }}><FilePlus2 size={21}/><strong>New project</strong><span>A clean page for your next idea</span></button><button className="action-card" onClick={() => fileInput.current?.click()}><FolderOpen size={21}/><strong>Open a file</strong><span>.flow, .txt, or .pseudo</span></button></div><div className="section-heading"><h3>Recent projects</h3><span>Stored in this browser</span></div><div className="saved-projects">{saved.length ? saved.map((p, i) => <button key={`${p.updatedAt}-${i}`} onClick={() => load(p)}><FileText size={18}/><div><strong>{p.title || 'Untitled project'}</strong><span>{p.source.split('\n').length} lines</span></div><ChevronRight size={16}/></button>) : <p className="empty-projects">Save a project or open an example to build your recent list.</p>}</div><p className="storage-note">Save a .flow file for a portable backup. Browser storage can be cleared by your browser.</p></Dialog>}
    {modal === 'export' && <Dialog title="Take your flowchart with you." eyebrow="EXPORT" onClose={closeModal}><p className="modal-description">Exporting <strong>{chart?.name}</strong> from “{title || 'Untitled project'}”. Exports include the whole chart, independent of canvas zoom.</p><div className="export-options">{[{ kind: 'svg', label: 'SVG', desc: 'Crisp vector artwork, at any size', tag: 'Recommended' }, { kind: 'png', label: 'PNG', desc: 'A high-resolution image for documents', tag: 'Image' }, { kind: 'pdf', label: 'Print / PDF', desc: 'Open the print dialog and save as PDF', tag: 'Document' }].map(o => <button className="export-option" key={o.kind} disabled={exportBusy} onClick={() => doExport(o.kind as 'svg' | 'png' | 'pdf')}><span className="export-file"><FileText size={22}/></span><div><strong>{o.label}</strong><span>{o.desc}</span></div><span className="export-tag">{o.tag}</span>{exportBusy ? <Loader2 className="spin" size={17}/> : <ArrowDownToLine size={17}/>}</button>)}</div><label className="checkbox-row"><input type="checkbox" checked={exportDark} onChange={e => setExportDark(e.target.checked)}/> Use a dark background for SVG and PNG</label><p className="storage-note">PDF fits the current chart onto one page. For large charts, SVG preserves readability at any zoom.</p><button className="secondary-button full" onClick={save}><Save size={16}/> Save editable project (.flow)</button></Dialog>}
    {modal === 'share' && <Dialog title="Share the logic." eyebrow="PROJECT LINK" onClose={closeModal}><p className="modal-description">This link contains a snapshot of your project. Anyone with it can open and edit their own copy. Changes afterward do not update the link.</p><label className="field-label" htmlFor="share-link">Project link</label><textarea className="share-input" id="share-link" readOnly value={shareLink} onFocus={e => e.target.select()}/><button className="primary-button full" onClick={() => copy(shareLink)}><Copy size={16}/>Copy link</button><div className="guide-note"><Link2 size={17}/><p>The project is encoded in the URL fragment and is not uploaded to a project server. Treat links as public when you share them.</p></div></Dialog>}
    {modal === 'settings' && <Dialog title="Make the workspace yours." eyebrow="SETTINGS" onClose={closeModal}><div className="setting-row"><div><h3>Workspace appearance</h3><p>A comfortable background for your editor.</p></div><button className="secondary-button" onClick={() => setDark(!dark)}>{dark ? <Moon size={16}/> : <Sun size={16}/>} {dark ? 'Dark' : 'Light'}</button></div><div className="setting-row"><div><h3>Flowchart canvas</h3><p>Separate from the editor’s appearance.</p></div><button className="secondary-button" onClick={() => setCanvasDark(!canvasDark)}>{canvasDark ? 'Dark' : 'Light'}</button></div><div className="setting-row"><div><h3>Keyboard shortcuts</h3><p>Save project <kbd>Ctrl / ⌘ S</kbd></p><p>Format code <kbd>Ctrl / ⌘ ⇧ F</kbd></p><p>Undo / redo <kbd>Ctrl / ⌘ Z / ⇧ Z</kbd></p></div></div><div className="guide-note"><ShieldCheck size={18}/><p>Codechart works locally in your browser. Projects use device-local storage; .flow files are your portable backups. No account, telemetry, or AI service is used.</p></div></Dialog>}
    <input ref={fileInput} type="file" hidden accept=".flow,.json,.txt,.pseudo" onChange={e => { const file = e.target.files?.[0]; if (file) void openFile(file); e.target.value = ''; }}/>
    {toast && <div className="toast" role="status"><CircleAlert size={17}/><span>{toast}</span><button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={15}/></button></div>}
  </div>;
}
function MouseIcon() { return <svg width="12" height="13" viewBox="0 0 12 13" fill="none" aria-hidden="true"><path d="M2 1v10l3-3 3 4 2-1-3-4h4L2 1Z" stroke="currentColor" strokeLinejoin="round"/></svg>; }
